### ISSUE TITLE
Quick Start issues

### ISSUE THREAD

**Issue by mike-zipit** [cloudposse/docs#122]
Documentation improvements for [Quick Start](https://docs.cloudposse.com/geodesic/module/quickstart/)

- [ ] Document that build-harness must first be installed
- [ ] Document to initialize the git repo and do an initial commit to master

**Comment by osterman** [comment]
@mike-zipit 

> Document to initialize the git repo and do an initial commit to master

Can you elaborate on what you're referring to?
