### ISSUE TITLE
Question about S3 Filesystem

### ISSUE THREAD

**Issue by mike-zipit** [cloudposse/docs#123]
## Question

Isn't this out of date?  I think this should reference goofys

**Comment by osterman** [comment]
Confirmed. That page is confusing and will fix it. 

https://docs.cloudposse.com/geodesic/s3fs/

**Comment by osterman** [comment]
I think we'll continue to refer to it as `s3fs` for clarity, as in it provides an "S3 filesystem". I think calling it `goofys` is more confusing, no?
