### ISSUE TITLE
Cannot Write Secrets to Chamber: AWSKMS; Status Code: 400; Error Code: NotFoundException

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#152]
## what
* Why can I add keys to chamber via geodesic but not using `aws-vault exec joany-dev-admin -- chamber write test key value`  I can read fine just not write
```
Error: InvalidKeyId: Alias arn:aws:kms:us-west-2:271462348125:alias/parameter_store_key is not found. (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: 40c97139-788f-11e8-932c-45e4f64721d4)
        status code: 400, request id: 5a6af5a5-6227-477c-bd80-ba63fe73c02d
```

## why
* The KMS key is wrong (e.g. `alias/parameter_store_key` is the default)

**Comment by ballou88** [comment]
You need to have `CHAMBER_KMS_KEY_ALIAS` set in your environment variables.
