### ISSUE TITLE
Kiam: error detecting arn prefix: aws metadata api not available

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#160]
## what
Trying to release kiam in prod, and running into the liveness probe issue referenced from the PR:
```
Liveness probe failed: Get http://172.20.125.153:8181/ping: dial tcp 172.20.125.153:8181: getsockopt: connection refused
```

```
➤  kubectl logs kiam-agent-pzvpt
{"level":"fatal","msg":"error creating server gateway: error waiting for address being available in the balancer: context deadline exceeded","time":"2018-07-02T15:05:28Z"}
```

The server also has problems:
```
{"level":"info","msg":"detecting arn prefix","time":"2018-07-02T17:17:12Z"}
{"level":"fatal","msg":"error creating listener: error detecting arn prefix: aws metadata api not available","time":"2018-07-02T17:17:13Z"}
```

## why
* The cause for this is typically one of two things:
  a) the TLS certs don't match the hostname. If using our script and helmfile, this should be mitigated.
  b) when upgrading from `kube2iam` to `kiam`, some `iptables` rules are orphaned that cause problems.

## fix
1.) make sure `kube2iam` helm release deleted
2) reboot all servers -> flush iptables rules
3) try again

**Comment by integrii** [comment]
I am having this issue on a fresh 1.11 cluster today, but I am not upgrading from kube2iam or running kiam-agent on any of the servers wherein kiam-server is running.  We are running the agent on nodes and the server on masters.

Only a single kiam-server instance is failing out of three.  Rebuilding the entire node does not fix the issue.
