### ISSUE TITLE
Versioned Docs

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#176]
## what
* In addition to publishing a release to `/`, we should publish a release to `/release/X.Y.Z` (E.g. `/release/0.1.0`)
* Use `robots.txt` to block indexing for `/release/*`

## why
* Allow customers to view stable documentation relative to their stack

**Comment by alebabai** [comment]
I've implemented it in the following way https://github.com/cloudposse/docs/commit/d6db5865489531ea51664ced358265f39af1d451
But there is a problem with root files sync.
> --delete  (boolean)  Files that exist in the destination but not in the
       source are deleted during sync.
When this flag is used all previous releases will be deleted from the repository.

**Comment by osterman** [comment]
Hrmmm... I think there is an —exclude argument; can you try that?

**Comment by osterman** [comment]
@alebabai somethings wrong.. we shouldn't be seeing `/releases/` in related section

![image](https://user-images.githubusercontent.com/52489/47758838-0dbe0080-dc6a-11e8-8cb5-63fb8bc38e4c.png)

**Comment by osterman** [comment]
https://docs.cloudposse.com/glossary/kubectl/

**Comment by alebabai** [comment]
@osterman hmm, it's seems that idea with content don't work well.
May be it's better to use full copy approach instead.
