### ISSUE TITLE
[terraform-aws-jenkins] provide terraform configuration with jenkins

### ISSUE THREAD

**Issue by Mkrishna7** [cloudposse/docs#214]
## Question

Details about your question...

## References
- <https://docs.cloudposse.com/terraform-modules/cicd/terraform-aws-jenkins/>

**Comment by osterman** [comment]
@Mkrishna7 thanks for opening this issue.

Yes, we need to update the documentation portal with links to the examples.

Here are (3) complete examples:

https://github.com/cloudposse/terraform-aws-jenkins/tree/master/examples

**Comment by osterman** [comment]
@alebabai use the `README.yaml` to generate this documentation.
