### ISSUE TITLE
[FIRING:1] Pod is restarting frequently

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#218]
## what
* Document remediation procedures

**Comment by goruha** [comment]
1. Find out name of pod that restarts frequently. 
You can find that info in alert manager message or in Prometheus UI
![screenshot_20181001_193140](https://user-images.githubusercontent.com/496956/46291583-b405e000-c5b0-11e8-939c-d1e25d50d381.png)
![screenshot_20181001_193251](https://user-images.githubusercontent.com/496956/46291628-d0a21800-c5b0-11e8-935e-7594624d0ffb.png)
2. Check that pod logs and events in `K8S Dashboard` or with `kubectl`
```
kubectl -n monitoring logs grafana-5566779cb5-9f8kq
```
```
kubectl -n monitoring describe pod grafana-5566779cb5-9f8kq
```
```
kubectl -n monitoring get -o yaml pod grafana-5566779cb5-9f8kq
```
3. Possible reasons
  * Error that makes the process of pod's container fail.
  * Miss configuration or wrong probes
