### ISSUE TITLE
Search Result Missing from Search Documentation

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#252]
## what
* Searching for "Makefile" doesn't return the most obvious page. I think it's maybe no included for some reason in the index.
* https://docs.cloudposse.com/?query=makefile
* https://docs.cloudposse.com/tools/make/ not in search results

**Comment by alebabai** [comment]
It could be found on this page https://docs.cloudposse.com/search/?query=makefile
For you query url there is a button `view all results`.

**Comment by alebabai** [comment]
But there is another bug with button "view all results".
When you entering text into search field, query param for this button remains the same (first letter).
E.g.
Search field: "makefile"
View all button has url `https://docs.cloudposse.com/search/?query=m`

**Comment by osterman** [comment]
@alebabai here's what I see

![image](https://user-images.githubusercontent.com/52489/48985963-fa645080-f0c2-11e8-88ac-a797d858ee55.png)

I don't see "https://docs.cloudposse.com/tools/make/" as a result

**Comment by osterman** [comment]
@alebabai try searching for "Understanding Makefiles" - no results

**Comment by alebabai** [comment]
![image](https://user-images.githubusercontent.com/19958900/49019180-6798e400-f19e-11e8-88fb-f2be4d945d8f.png)

![image](https://user-images.githubusercontent.com/19958900/49019159-57810480-f19e-11e8-9af8-2d4de82ca64c.png)

![image](https://user-images.githubusercontent.com/19958900/49019111-3a4c3600-f19e-11e8-8c36-76e49cffc340.png)
