### ISSUE TITLE
Clean Up Page List

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#262]
## what

![image](https://user-images.githubusercontent.com/52489/48924674-c1806d80-ee6f-11e8-9160-6a5af62aef13.png)

## why
* it's so messy / cluttered
* don't like the shaded boxes.
* make the tags look like `#tags`

**Comment by osterman** [comment]
Get rid of left side padding/margin

![image](https://user-images.githubusercontent.com/52489/48986095-018c5e00-f0c5-11e8-94ec-91c76d4b97d6.png)

**Comment by osterman** [comment]
- [ ] remove float on "read more"
- [ ] drop background color

**Comment by osterman** [comment]
Need some spacing here in between title a content

![image](https://user-images.githubusercontent.com/52489/48986120-56c86f80-f0c5-11e8-8ad7-81b5653ca9cb.png)

**Comment by finnsky** [comment]
that page has lot of dependenicies. like faq page. i have to cleanup lot of additional things here
