### ISSUE TITLE
Fix RSS pubDate

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#264]
## what
* pubDate is wrong (make it ctime)

## references
* https://docs.cloudposse.com/index.xml

**Comment by alebabai** [comment]
Hugo adheres to the RSS 2.0 Specification.
https://cyber.harvard.edu/rss/rss.html

> All date-times in RSS conform to the Date and Time Specification of RFC 822, with the exception that the year may be expressed with two characters or four characters (four preferred).

**Comment by alebabai** [comment]
Most likely the problem is that a lot of documents doesn't have pubDate property
