### ISSUE TITLE
Fix Bullet Points

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#273]
## what

![image](https://user-images.githubusercontent.com/52489/48983910-b022a580-f0a9-11e8-9c98-ab2dba6451b3.png)

## why
* It appears markdown is not being rendered

## references
* https://docs.cloudposse.com/glossary/docker-registry/

**Comment by alebabai** [comment]
By the way - here is good md-linter for visual code
https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
