### ISSUE TITLE
DevOps Onboarding Document

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#300]
## what
* Describe everything a new hire should review 

## why
* to get started quickly
* to get acquainted with tools and techniques needed to perform job

**Comment by osterman** [comment]
## maintenance
* [Upgrading kops clusters](https://docs.cloudposse.com/geodesic/kops/upgrade-cluster/)

**Comment by whyevenquestion1t** [comment]
@osterman - is this still relevant? Can I team up with someone to make this document a reality? Let me know if there's any change in what an onboarding document should contain. 

I am familiar with Geodesic, recently learned the basics of K8s, and can do stuff with Terraform and Terragrunt in case you need me to do something else.
