### ISSUE TITLE
Implement Shortcode for Collapsable Output

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#319]
## what

![image](https://user-images.githubusercontent.com/52489/49962870-4e48a500-fecb-11e8-9b3b-b9c89b0439de.png)

![image](https://user-images.githubusercontent.com/52489/49962882-54d71c80-fecb-11e8-836d-49dd8ecee732.png)
 
## why
* Our documentation gets unwieldy with too much information. This makes it intimidating to look at. While at the same time, the more information we can stick in the page, the more "Searchable" it is and the better the expectations can be set for the user. 
* We've started using the tags on github and it works well

## references
* https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f

**Comment by osterman** [comment]
![image](https://user-images.githubusercontent.com/52489/49963053-d0d16480-fecb-11e8-8b32-d7fdc82646e8.png)


Maybe we don't need to do anything? Is this a browser feature?? @finnsky

**Comment by finnsky** [comment]
<details> is valid element here

**Comment by finnsky** [comment]
@osterman 
only one thing here. no IE out of box https://caniuse.com/#feat=details
we may add polyfill. or ignore IE.  
also i don't think that shortcode is needed for 2 tags.
