### ISSUE TITLE
Add External Link Icon

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#320]
## what

![image](https://user-images.githubusercontent.com/52489/49963505-075baf00-fecd-11e8-8b24-421fe3ce0e16.png)

* I'm not crazy about my design in this mock up. It's just trying to convey what I want.

## why
* It's annoying when clicking on header links and getting taken to a new site by surprise
* It's common practice to indicate when links to to an external site

**Comment by finnsky** [comment]
@osterman i think most obvious will be icon after link name 
https://fontawesome.com/icons/external-link?style=solid

**Comment by osterman** [comment]
Let's hold off on this one. I think it will look too ugly. Haha.
