### ISSUE TITLE
Responsive Design for Table of Contents 

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#354]
## what
* On my MBP 13" the pages look like this:

![image](https://user-images.githubusercontent.com/52489/50663646-3232a380-0f5f-11e9-8c0d-fa83f77fae3c.png)

## references
* https://docs.cloudposse.com/kubernetes/resource-management/

**Comment by finnsky** [comment]
kind of flexbox bug
[![Image from Gyazo](https://i.gyazo.com/7c4856c100a85d4e0faf23301faf908b.gif)](https://gyazo.com/7c4856c100a85d4e0faf23301faf908b)
