### ISSUE TITLE
Implement Hamburger Menus for Mobile

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#38]
## what
* Should display hamburger menu for mobile
* Should hide calendly link on mobile
* Use https://github.com/mac81/pure-drawer/

**Comment by finnsky** [comment]
please define logic.
https://gyazo.com/fec842689a8e0a955b77a8e4e9c8574e 
1) we may have 2 menus same type?
2) we may have 2 menus different types?
3) we have to group them in one menu?
or something else

**Comment by finnsky** [comment]
![2menus](https://user-images.githubusercontent.com/4370955/43684218-d661cc88-98bd-11e8-8c48-25347db9e00c.gif)
inline image:)
