### ISSUE TITLE
Only Deploy on Tagged Releases

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#46]
## what
* Do not deploy to S3 for every merge to master

## why
* This will trigger algolia reindexing 
* Not all changes (e.g. Updating README.md) require redeployment

**Comment by osterman** [comment]
@aknysh @goruha @sarkis any thoughts on this?

**Comment by aknysh** [comment]
I agree, we don't need to deploy for every merge to master or every commit.
Only when we tag a new release, then we want a new version to be deployed.
That will provide more consistency and control.

**Comment by osterman** [comment]
@aknysh can you update the pipeline to work this way?
