### ISSUE TITLE
Description is not properly rendered

### ISSUE THREAD

**Issue by 3h4x** [cloudposse/docs#491]
In https://docs.cloudposse.com/terraform/ there is failed rendering under "Terraform Tips & Tricks"

<img width="1037" alt="Screenshot 2020-07-30 at 16 56 52" src="https://user-images.githubusercontent.com/6998565/88951537-6cc50500-d296-11ea-8488-1599b3decc93.png">

**Comment by milldr** [comment]
major refactor since this issue. Please see the latest: https://docs.cloudposse.com/components/
