### ISSUE TITLE
Consider Adding Line Numbers to Code Blocks

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#67]
## what
* Prefix code blocks with line numbers

## why
* Make it easier to reference lines of code

## references
* https://www.sylvaindurand.org/using-css-to-add-line-numbering/
* Example: https://guides.emberjs.com/v2.12.0/tutorial/deploying/

**Comment by finnsky** [comment]
suggested css way assumed that every line of code is wrapped into <code> 
but on ember example code has js attached span with numbers. 
We have themes/hugo-theme-docdock/static/js/highlight.pack.js but it is not supports http://highlightjs.readthedocs.io/en/latest/line-numbers.html line numbers, so possible solutions:

1. manage it with customs js.
2. cut code lines in separated code elements
3. use some external js lib.
